Validate missing scripts exit codes.

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -100,6 +100,9 @@ if [[ -n "$DB_RESTORE_TARGET" ]]; then
     for i in $(ls /scripts.d/post-restore/*.sh); do
       if [ -x $i ]; then
         DB_RESTORE_TARGET=${DB_RESTORE_TARGET} DB_DUMP_DEBUG=${DB_DUMP_DEBUG} $i
+        if [ $? -gt 0 ]; then
+            echo "post-restore: script $i failed with exit code: $?" && exit 1
+        fi
       fi
     done
   fi
@@ -140,6 +143,9 @@ else
       for i in $(ls /scripts.d/pre-backup/*.sh); do
         if [ -x $i ]; then
           NOW=${now} DUMPFILE=${TMPDIR}/${TARGET} DUMPDIR=${uri[path]} DB_DUMP_DEBUG=${DB_DUMP_DEBUG} $i
+          if [ $? -gt 0 ]; then
+              echo "pre-backup: script $i failed with exit code: $?" && exit 1
+          fi
         fi
       done
     fi
@@ -163,6 +169,9 @@ else
       for i in $(ls /scripts.d/post-backup/*.sh); do
         if [ -x $i ]; then
           NOW=${now} DUMPFILE=${TMPDIR}/${TARGET} DUMPDIR=${uri[path]} DB_DUMP_DEBUG=${DB_DUMP_DEBUG} $i
+          if [ $? -gt 0 ]; then
+              echo "post-backup: script $i failed with exit code: $?" && exit 1
+          fi
         fi
       done
     fi
